# Generated by Django 2.1.7 on 2019-03-13 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='VideoUrl',
            field=models.URLField(),
        ),
        migrations.AlterField(
            model_name='video',
            name='name',
            field=models.CharField(max_length=32),
        ),
    ]
